//
//  Candle.h
//  New Image
//
//  Created by Thomas Denney on 28/08/2013
//  Copyright 2013 Thomas Denney
//  This code was generated by Opacity Express. You may use or modify it in any way.
//

#include <CoreGraphics/CoreGraphics.h>

extern const CGFloat kCandleDrawingFunctionWidth;
extern const CGFloat kCandleDrawingFunctionHeight;

extern void CandleDrawingFunction(CGContextRef context, CGRect bounds);
