//
//  Cake.h
//  New Image
//
//  Created by Thomas Denney on 26/08/2013
//  Copyright 2013 Thomas Denney
//  This code was generated by Opacity Express. You may use or modify it in any way.
//

#import <UIKit/UIKit.h>

extern const CGFloat kMyViewWidth;
extern const CGFloat kMyViewHeight;

@interface MyView : UIView

@end
